import Head from "next/head";
import PageWrapper from "@/components/PageWrapper";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ArtworkGrid from "@/components/ArtworkGrid";
import { Artwork as IArtwork } from "@/types";
import AsciiCanvas from "@/components/AsciiCanvas";
import Artwork from "@/components/Artwork";
import ArtworkPlayer from "@/components/ArtworkPlayer";
import ArtworkPlayerProvider from "@/context/ArtworkPlayerProvider";

interface ArtworkProps {}

export default function ArtworkPage({}: ArtworkProps) {
  const artworkList: IArtwork[] = [
    {
      id: 0,
      imageSrc: "prox.jpg",
      date: new Date(),
      musicalKey: "c#",
      bpm: 154,
    },
    {
      id: 1,
      imageSrc: "prox.jpg",
      date: new Date(),
      musicalKey: "c#",
      bpm: 154,
    },
    {
      id: 2,
      imageSrc: "prox.jpg",
      date: new Date(),
      musicalKey: "c#",
      bpm: 154,
    },
    {
      id: 3,
      imageSrc: "prox.jpg",
      date: new Date(),
      musicalKey: "c#",
      bpm: 154,
    },
  ];
  return (
    <>
      <Head>
        <title>BINARY SELECTION</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ArtworkPlayerProvider>
        <PageWrapper>
          <Header />
          <main className="flex flex-1 flex-col justify-center items-center text-sm text-neutral-300">
            {/*<ArtworkGrid artworkList={artworkList} />*/}
            <Artwork />
            <ArtworkPlayer />
          </main>
          <Footer />
        </PageWrapper>
      </ArtworkPlayerProvider>
    </>
  );
}
