import Head from "next/head";
import PageWrapper from "@/components/PageWrapper";
import Header from "@/components/Header";
import TrackGrid from "@/components/TrackGrid";
import Footer from "@/components/Footer";

export default function CartPage() {
  return (
    <>
      <Head>
        <title>BINARY SELECTION</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWrapper>
        <Header />
        <main className="flex flex-1 flex-col justify-center items-center text-sm text-neutral-300">
          <p>IN CART</p>
          <ul>
            <li></li>
          </ul>
        </main>
        <Footer />
      </PageWrapper>
    </>
  );
}
