import Head from "next/head";
import PageWrapper from "@/components/PageWrapper";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import FirebaseAuthProvider from "@/context/FirebaseAuthProvider";
import Checkout from "@/components/Checkout";

export default function CheckoutPage() {
  return (
    <>
      <Head>
        <title>BINARY SELECTION</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FirebaseAuthProvider>
        <PageWrapper>
          <Header />
          <main className="flex flex-1 flex-col justify-center items-center text-sm text-neutral-300">
            <Checkout />
          </main>
          <Footer />
        </PageWrapper>
      </FirebaseAuthProvider>
    </>
  );
}
