import Head from "next/head";
import { Inter } from "@next/font/google";
import PageWrapper from "@/components/PageWrapper";
import { TrackPlayerProvider } from "@/context/TrackPlayerProvider";
import AsciiCanvas from "@/components/AsciiCanvas";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Avdio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TrackPlayerProvider>
        <PageWrapper>
          <main className="flex flex-col justify-center items-center min-h-screen">
            <div>
              <div className="flex justify-between text-sm text-neutral-300 mb-12">
                <Link href="#" className="">
                  ‹ PREVIOUS
                </Link>
                <Link href="#" className="">
                  NEXT ›
                </Link>
              </div>
              <div className="flex items-center">
                <div className="text-sm text-neutral-300 mr-12">
                  <p className="">&quot;0&quot;</p>
                  <p className="">JAN 24 2023</p>
                  <p className="">KEY: C#</p>
                  <p className="mb-8">BPM: 154</p>
                  <Link
                    href="#"
                    className="text-sm text-emerald-200 border outline: p-2 hover:bg-emerald-900"
                  >
                    PURCHASE
                  </Link>
                </div>
                <AsciiCanvas imageSrc={"prox.jpeg"} size="lg" />
              </div>
            </div>
          </main>
        </PageWrapper>
      </TrackPlayerProvider>
    </>
  );
}
