import Head from "next/head";
import { Inter } from "@next/font/google";
import PageWrapper from "@/components/PageWrapper";
import TrackSection from "@/components/TrackSection";
import TrackControl from "@/components/TrackControl/TrackControl";
import { TrackPlayerProvider } from "@/context/TrackPlayerProvider";
import { getAllFilesFromBucket, getFileFromBucket } from "@/lib/s3";
import { Simulate } from "react-dom/test-utils";
import { useEffect, useState } from "react";
import TrackList from "@/components/TrackList";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ files }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TrackPlayerProvider>
        <PageWrapper>
          <main className="flex justify-center items-center min-h-screen">
            <TrackSection
              tracks={[
                {
                  title: "Stop Breathing",
                  audioSrc: `data:audio/mpeg;base64,${files[2]}`,
                  imageSrc: "/",
                  datePosted: new Date(),
                  audioLength: 224,
                  shareHyperlink: "/",
                  downloadHyperLink: "/",
                },
              ]}
            />
            <TrackControl />
          </main>
        </PageWrapper>
      </TrackPlayerProvider>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const files = await getAllFilesFromBucket();
    return { props: { files } };
  } catch (error) {
    console.log(error);
    return { props: { files: "" } };
  }
}
