import Head from "next/head";
import { Inter } from "@next/font/google";
import PageWrapper from "@/components/PageWrapper";
import Link from "next/link";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>BINARY SELECTION</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWrapper>
        <Header />
        <main className="flex flex-1 flex-col justify-center items-center">
          <div>
            <div className="flex justify-between text-sm text-neutral-300 mb-12">
              <Link className="hover:text-white" href="#">
                ⇜ PREVIOUS
              </Link>
              <Link className="hover:text-white" href="#">
                NEXT ⇝
              </Link>
            </div>
          </div>
        </main>
        <Footer />
      </PageWrapper>
    </>
  );
}
